### ISSUE TITLE
laserbox.scad cannot be compiled

### ISSUE THREAD

**Issue by coldpower** [lijon/jl_scad#1]
hi mate,

Your project seems very interesting and gives some ideas of how BOSL2 library can be used - great work!

However, from very begin i hit few issues.

im using OpenSCAD-2024.02.20-x86-64 (windows 64 version), latest BOSL2 (https://github.com/BelfrySCAD/BOSL2/tree/master), latest commit hash is 15769fd04eba884937f9e4e5d63572ed146021b4

Seems like you've used one of previous commits of BOSL2? (its shame they dont make releases - means there is no simple way to refer to the particular version of BOSL2).

Here is openscad console output

`OpenSCAD 2024.02.20 
https://www.openscad.org/
 
Copyright (C) 2009-2024 The OpenSCAD Developers
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 
Loaded design 'D:/hobby/jl_scad/example.scad'.
 
Parsing design (AST generation)...
Used file cache size: 1 files
Compiling design (CSG Tree generation)...
ECHO: "BOX SIZE", [54, 44, 22]
[WARNING: Ignoring unknown function 'get_fn' in file jl_scad/parts.scad, line 32](https://github.com/lijon/jl_scad/issues/32,D:/hobby/jl_scad/jl_scad/parts.scad)
[ERROR: Assertion '(is_int(splinesteps) && (splinesteps > 0))' failed: "splinesteps must be a positive integer" in file jl_scad/BOSL2/beziers.scad, line 1253](https://github.com/lijon/jl_scad/issues/1253,D:/hobby/jl_scad/jl_scad/BOSL2/beziers.scad)
[TRACE: called by 'bezier_vnf_degenerate_patch' in file jl_scad/BOSL2/rounding.scad, line 2261](https://github.com/lijon/jl_scad/issues/2261,D:/hobby/jl_scad/jl_scad/BOSL2/rounding.scad)
[TRACE: called by 'rounded_prism' in file jl_scad/BOSL2/rounding.scad, line 2144](https://github.com/lijon/jl_scad/issues/2144,D:/hobby/jl_scad/jl_scad/BOSL2/rounding.scad)
[TRACE: assignment to 'result' in file jl_scad/BOSL2/rounding.scad, line 2144](https://github.com/lijon/jl_scad/issues/2144,D:/hobby/jl_scad/jl_scad/BOSL2/rounding.scad)
[TRACE: called by 'rounded_prism' in file jl_scad/parts.scad, line 39](https://github.com/lijon/jl_scad/issues/39,D:/hobby/jl_scad/jl_scad/parts.scad)
[TRACE: call of 'baseshape(p = [[27, -22], [-27, -22], [-27, 22], [27, 22]], inset = 0, flat_bottom = false, height = 13)' in file jl_scad/parts.scad, line 34](https://github.com/lijon/jl_scad/issues/34,D:/hobby/jl_scad/jl_scad/parts.scad)
[TRACE: called by 'baseshape' in file jl_scad/parts.scad, line 47](https://github.com/lijon/jl_scad/issues/47,D:/hobby/jl_scad/jl_scad/parts.scad)
[TRACE: called by 'children' in file jl_scad/BOSL2/color.scad, line 47](https://github.com/lijon/jl_scad/issues/47,D:/hobby/jl_scad/jl_scad/BOSL2/color.scad)
[TRACE: call of 'recolor(c = "#ccc")' in file jl_scad/BOSL2/color.scad, line 43](https://github.com/lijon/jl_scad/issues/43,D:/hobby/jl_scad/jl_scad/BOSL2/color.scad)
[TRACE: called by 'recolor' in file jl_scad/parts.scad, line 46](https://github.com/lijon/jl_scad/issues/46,D:/hobby/jl_scad/jl_scad/parts.scad)
[TRACE: called by 'difference' in file jl_scad/parts.scad, line 45](https://github.com/lijon/jl_scad/issues/45,D:/hobby/jl_scad/jl_scad/parts.scad)
[TRACE: call of 'open_round_box(size = [54, 44, 13], rsides = 5, rbot = 1, wall_side = 2, wall_bot = 1, rim_height = 2, rim_wall = 1, rim_inside = true, rsides_inside = undef, rbot_inside = 2, k = 0.92, rim_snap = false, rim_snap_ofs = 1.1, rim_snap_depth = 0.2, rim_snap_height = 0.2, inside_color = "#a99", outside_color = "#ccc")' in file jl_scad/parts.scad, line 23](https://github.com/lijon/jl_scad/issues/23,D:/hobby/jl_scad/jl_scad/parts.scad)
[TRACE: called by 'open_round_box' in file jl_scad/parts.scad, line 315](https://github.com/lijon/jl_scad/issues/315,D:/hobby/jl_scad/jl_scad/parts.scad)
Compiling design (CSG Products generation)...
Geometries in cache: 0
Geometry cache size in bytes: 0
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 1 elements!
Compile and preview finished.
Total rendering time: 0:00:03.462`

**Comment by lijon** [comment]
I removed `get_fn()` since it's already in BOSL2 as `segs()`, but forgot one place where it was used.
Fixed in 5bb27fcffa206fc7f486618a5acea409883ac6a6

**Comment by coldpower** [comment]
All seems good now, thanks a heap!
