### ISSUE TITLE
ERROR: Parser error: syntax error in file box.scad, line 35 

### ISSUE THREAD

**Issue by veduket** [lijon/jl_scad#2]
Hello @lijon,
I was trying to run the basic example from the README.
I have installed the required library [BOSL2](https://github.com/BelfrySCAD/BOSL2/tree/master) as per the documentation.

```
include <jl_scad/box.scad>
include <jl_scad/parts.scad>
box_make(explode=30)
box_shell_base_lid([20,20,20])
{
    box_part(BOT, CENTER) cube(5,anchor=BOTTOM); // add a cube in the center of the base.
}
```
But I'm getting the error 

> 
> ERROR: Parser error: syntax error in file box.scad, line 35  
> Execution aborted

Regards

**Comment by mohnen** [comment]
Same for me

**Comment by mohnen** [comment]
I created a pull request with a fix

**Comment by lijon** [comment]
Probably a difference in OpenSCAD versions then. I'm using OpenSCAD 2024.01.28. I would be surprised if nothing else breaks in 2021 version, but will merge the pull request anyway since it doesn's hurt. :)

**Comment by veduket** [comment]
Thank you both @mohnen and @lijon for the fix. 
And @lijon, I think the version may be the culprit, I'm using   **OpenSCAD version 2021.01**.
I'll update OpenSCAD and test it.
Thanks again.
